### ISSUE TITLE
Derivation path for Sentinel

### ISSUE THREAD

**Issue by HS-Joe** [eco-stake/restake#463]
Hey guys,

I have a warning for sentinel about not using the preferred derivation path, though Keplr shows me the same wallet address.
When setting 
```
 "autostake": {
      "correctSlip44": true
    }
```
and running the script again, it logs a bot wallet address I don't know about (i.e. not the one showing up in keplr with this mnemonic.
Could you check that?
Had the same warning for lumnetwork, and in this case the displayed wallet did match the one in keplr, so for lum it seems indeed correct.

**Comment by ChihuahuaChain** [comment]
Same error using sentinel but showing the correct address and can get balance as in keplr

**Comment by tombeynon** [comment]
Thanks guys - by the sound of it then, the `slip44` path [in Chain Registry](https://github.com/cosmos/chain-registry/blob/master/sentinel/chain.json#L9) is incorrect for Sentinel. Or at least doesn't match what Keplr is using, and Keplr supports Sentinel natively.

The solution for you guys is to use `slip44: 118` explicitly in your `networks.local.json` file. REStake uses that by default now, which is why you see the correct address when you don't set `correctSlip44: true`. However this will change in the future when we use the Chain Registry version by default, and I can't be sure if the Sentinel mismatch will be solved by then.

Keeping this open for visibility/reference.

**Comment by HS-Joe** [comment]
@tombeynon OK thanks for the advice, it is working.
Also had to use `"correctSlip44": true` for persistence and desmos, is that expected?

**Comment by tombeynon** [comment]
That's correct. You can see the `slip44` in the chain-registry, if it's different than 118 then it will need this config. 

In the future 'correctSlip44' will be the default, which is why it's so noisy in the script.

**Comment by HS-Joe** [comment]
OK thanks for the explanation. Should i close this issue?

**Comment by tombeynon** [comment]
Chain Registry has merged the correct Slip44 path now
