### ISSUE TITLE
error on enable when withdraw addresses are present

### ISSUE THREAD

**Issue by joeabbey** [eco-stake/restake#47]
Currently restake ignores withdraw addresses

Detect the presence of a withdraw address, and error on enable.

**Comment by tombeynon** [comment]
We could leave it up to the user too - warn them that while they have a different withdraw address, the operator will only be able to restake if they have enough balance to cover the delegation, otherwise the whole transaction will be skipped. 

We'll have to handle that case either way, as user could grant and then set withdraw address in the future, not knowing the impact. I believe the autostaking TX will fail entirely, so no claim happens, if there wasn't enough balance (needs testing)

**Comment by tombeynon** [comment]
Need to skip users now we have batched transactions as it causes the whole batch to fail. #48 ignores them, just need to warn the user in the UI to resolve this

**Comment by tombeynon** [comment]
Improved in #305
