### ISSUE TITLE
Echelon auto restake not working

### ISSUE THREAD

**Issue by jambulmerah** [eco-stake/restake#527]
please fix for the stuck echelon auto compound feature

**Comment by tombeynon** [comment]
Hey is there a specific error you're receiving for Echelon?

**Comment by umitbeniz** [comment]
Hey @tombeynon, 
I tested now. 
The problem is probably that unable to auto gas adjustment.

`Failed to broadcast: Error when broadcasting tx 61F8176AF4639CD12F81EE1EE202075BC9F4BCA67E7ADE4E2EA450E87201ACDF at height 0. Code: 13; Raw log: insufficient fees; got: 2835aechelon required: 283440000000000aechelon: insufficient fee`
