### ISSUE TITLE
Use feegrant for paying fees. Remove fee burden on the validators.

### ISSUE THREAD

**Issue by anilCSE** [eco-stake/restake#99]
Fee-grant enables one to use fees from other accounts. Here instead of using hot wallet for fees, let delegators pay fees for their transactions. If there are 100k delegators, fees for a validator would be very high. It's a benefit for delegators, and competely optional for them. So they can pay fees

**Comment by digitaladapt** [comment]
I think validators that aren't willing to cover the transaction cost shouldn't offer restake.

Personally, from an end-user perspective, I'd be weary of any authz grant requesting the ability to charge fees to my wallet.
It would also run the risk of emptying someone's wallet, since their rewards are being restaked and not flowing back into their wallet.

From a validator perspective, enabling restake helps increase how much people deletgate to you, and it increases your commission over time, which I feel is a fair compensation for footing the transaction fee.

* Disclaimer, I'm not in charge of this project, but I provide restake on my lum-network validator, and on other networks, I use it as an end-user.

**Comment by anilCSE** [comment]
> I think validators that aren't willing to cover the transaction cost shouldn't offer restake.
> 
> Personally, from an end-user perspective, I'd be weary of any authz grant requesting the ability to charge fees to my wallet. It would also run the risk of emptying someone's wallet, since their rewards are being restaked and not flowing back into their wallet.
> 
> From a validator perspective, enabling restake helps increase how much people deletgate to you, and it increases your commission over time, which I feel is a fair compensation for footing the transaction fee.
> 
> * Disclaimer, I'm not in charge of this project, but I provide restake on my lum-network validator, and on other networks, I use it as an end-user.

Sounds fair. How about giving it as an option. Either validator can chose to payfee or use feegrant. Delegators can limit the fees that an account can use. So no risk of emptying the account for fees

**Comment by tombeynon** [comment]
Totally agree with both of you tbh. The awesome thing about restake is it provides validators a new service they can offer, and the more we can make that customisable/flexible the better. Larger validators might not want to shoulder the cost of fees since they don't need to attract the delegations, but giving delegators the option to still have autocompounding if they pay fees is a nice alternative. 

Another option for delegator is to run restake themselves, which can be made a lot easier than it is currently. But I like the validators providing this service, it's easy for us.

Anyway, definitely keeping this open to investigate and add feegrant for sure, but I have a few other things to sort first

**Comment by frostbyte3** [comment]
To add this an an option you'd need to guarantee to each delegator that the reward of continuously re-staking at potentially volatile APRs is more than the increase in possibly mutable fees incurred due to the frequency of re-staking.

As this would likely be unprofitable for wallets under a certain threshold on most blockchains, the validator would need to make a re-staking plan on a per address basis to ensure this is profitable for that delegate's wallet size. This plan should be clearly reported to the delegator so they fully understand the terms of their re-stake strategy.

It's also important to consider that the Authz grant expires after 1 year, so the delegate may be issuing the initial grant for something that doesn't happen within that timeframe.

@tombeynon

**Comment by tombeynon** [comment]
It definitely raises a number of implementation questions. The recent batch autostake transactions have improved fees quite a bit too. I wonder if introducing something like this would be more confusing than it's worth, but will keep this open for any further comments on costs for validators. The larger validators might be suffering this more than others.

**Comment by tombeynon** [comment]
Given the challenges involved ensuring a feegrant was worthwhile for the user, and the improvements in gas costs for the validators in #293, #483 and #487, I think this is resolved enough to close this issue.
